-- Creating Database
Create Database customer_trend_analysis

-- Using the Database
Use customer_trend_analysis

-- Customer Data Table
Select * from customer_data_eda


----       Questions      -----

-- Q1. What is the total revenue generated by male vs. female customers? 
Select gender , SUM(purchase_amount) as revenue
From customer_data_eda 
Group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select customer_id, purchase_amount 
From customer_data_eda 
Where discount_applied = 'Yes' and purchase_amount >=(Select AVG(purchase_amount) from customer_data_eda)


-- Q3. Which are the top 5 products with the highest average review rating?
Select Top 5 item_purchased , Round(AVG(CAST(review_rating As Decimal(5,2))),2) As [Average Product Rating]
From customer_data_eda
Group by item_purchased
Order by AVG(CAST(review_rating As Decimal(5,2))) Desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select shipping_type, Round(AVG(purchase_amount) , 2) As Avg_purchase
From customer_data_eda
Where Shipping_type IN ('Standard','Express')
Group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status,
    Count(customer_id) as total_customers,
    Round(Avg(purchase_amount), 2) as avg_spend,
    Round(Sum(purchase_amount), 2) as total_revenue
From customer
Group by subscription_status
Order by total_revenue desc, avg_spend desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select Top 5
    item_purchased,
    Round(100.0 * SUM(Case When discount_applied = 'Yes' Then 1 Else 0 End) / Count(*), 2) AS discount_rate
From customer_data_eda
Group by item_purchased
Order by discount_rate desc


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
With customer_type as (
    Select customer_id, previous_purchases,
        Case 
            When previous_purchases = 1 Then 'New'
            When previous_purchases between 2 and 10 Then 'Returning'
            Else 'Loyal'
        End as customer_segment
    From customer_data_eda
)

Select customer_segment, Count(*) as number_of_customers
From customer_type
Group by customer_segment


--Q8. What are the top 3 most purchased products within each category? 
With item_counts as (
    Select category, item_purchased,
        Count(customer_id) as total_orders,
        Row_Number() Over (
            Partition by category 
            Order by Count(customer_id) desc
        ) as item_rank
    From customer_data_eda
    Group by category, item_purchased
)

Select item_rank, category, item_purchased, total_orders
From item_counts
Where item_rank <= 3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status, Count(customer_id) as repeat_buyers
From customer_data_eda
Where previous_purchases > 5
Group by subscription_status


--Q10. What is the revenue contribution of each age group? 
Select age_group, Sum(purchase_amount) as total_revenue
From customer
Group by age_group
Order by total_revenue desc